# Check out Codecov at: https://codecov.io/

coverage:
  precision: 2
  round: down
  range: 80...100
  status:
    project:
      default: false
      source:
        paths:
          - src/

comment:
  layout: diff, files
  behavior: once # "update, if exists. Otherwise post new. Skip if deleted."
  require_changes: true # "only post the comment if coverage changes"
  require_base: no
  require_head: yes

ignore:
  - tests/**/*
