# Check out Dependabot at: https://github.com/dependabot

version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    open-pull-requests-limit: 1
    schedule:
      interval: daily
      time: "04:00"
    assignees:
      - ericcornelissen
    labels:
      - dependencies
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 1
    schedule:
      interval: daily
      time: "04:00"
    assignees:
      - ericcornelissen
    labels:
      - ci/cd
      - dependencies
