# SPDX-License-Identifier: MIT-0

FROM docker.io/rust:1.89.0-alpine3.21

RUN apk add --no-cache \
	bash git just libressl-dev musl-dev perl \
	&& \
	git config --global --add safe.directory /rust-rm

RUN cargo install \
	cargo-all-features@1.10.0 \
	cargo-deny@0.18.0 \
	cargo-mutants@25.0.0 \
	cargo-tarpaulin@0.32.0

WORKDIR /rust-rm
COPY ./ ./

ENTRYPOINT ["/bin/bash"]
