# Check out cargo-deny at: https://github.com/EmbarkStudios/cargo-deny

[advisories]
ignore = []
unmaintained = "warn"
vulnerability = "deny"
yanked = "deny"

[licenses]
allow = [
    "Apache-2.0",
    "MIT",
    "BSD-3-Clause",
    "Unicode-DFS-2016",
]
confidence-threshold = 0.8
deny = []
default = "deny"
include-dev = true
unlicensed = "deny"
